In [9]:
import pandas as pd
path = '/home/kalyan/Desktop/datasetIRB2400.csv'

# Read the data
data = pd.read_csv(path)
data.head(1000)

,x,y,z,yaw,pitch,roll,q1_in,q2_in,q3_in,q4_in,q5_in,q6_in,q1_out,q2_out,q3_out,q4_out,q5_out,q6_out
0,-80.9148,-121.7499,1896.4867,-0.6941,0.9229,-1.4411,-2.2407,-0.7975,0.6551,-3.2989,1.1212,5.7052,-2.2347,-0.8949,0.6113,-3.2841,1.2117,5.6792
1,-80.9148,-121.7499,1896.4867,-0.6941,0.9229,-1.4411,-2.2233,-0.8511,0.5966,-3.2320,1.1662,5.6429,-2.2347,-0.8949,0.6113,-3.2841,1.2117,5.6792
2,-80.9148,-121.7499,1896.4867,-0.6941,0.9229,-1.4411,-2.2567,-0.9468,0.5820,-3.3165,1.1220,5.5944,-2.2347,-0.8949,0.6113,-3.2841,1.2117,5.6792
3,-80.9148,-121.7499,1896.4867,-0.6941,0.9229,-1.4411,-2.1557,-0.8205,0.5532,-3.1993,1.2697,5.7474,-2.2347,-0.8949,0.6113,-3.2841,1.2117,5.6792
4,-80.9148,-121.7499,1896.4867,-0.6941,0.9229,-1.4411,-2.3267,-0.9279,0.6722,-3.2867,1.2266,5.6304,-2.2347,-0.8949,0.6113,-3.2841,1.2117,5.6792
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,-73.9893,-199.3347,1784.3901,3.0938,0.1018,-0.8274,1.1058,-0.9931,0.2418,1.6215,-0.2784,-5.9906,1.1271,-0.9837,0.1822,1.5376,-0.2224,-5.9040
996,-73.9893,-199.3347,1784.3901,3.0938,0.1018,-0.8274,1.0347,-1.0182,0.2333,1.4762,-0.1599,-5.9433,1.1271,-0.9837,0.1822,1.5376,-0.2224,-5.9040
997,-73.9893,-199.3347,1784.3901,3.0938,0.1018,-0.8274,1.1458,-0.9821,0.1172,1.5324,-0.1436,-5.8651,1.1271,-0.9837,0.1822,1.5376,-0.2224,-5.9040
998,-73.9893,-199.3347,1784.3901,3.0938,0.1018,-0.8274,1.1735,-0.9190,0.1960,1.5981,-0.2316,-5.8881,1.1271,-0.9837,0.1822,1.5376,-0.2224,-5.9040
999,-73.9893,-199.3347,1784.3901,3.0938,0.1018,-0.8274,1.1044,-0.9590,0.2388,1.5610,-0.3223,-5.9920,1.1271,-0.9837,0.1822,1.5376,-0.2224,-5.9040

In [5]:
#chek for null values
data.isnull().sum()

x         0
y         0
z         0
yaw       0
pitch     0
roll      0
q1_in     0
q2_in     0
q3_in     0
q4_in     0
q5_in     0
q6_in     0
q1_out    0
q2_out    0
q3_out    0
q4_out    0
q5_out    0
q6_out    0
dtype: int64